apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-powercap.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-powercap.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: k8s-powercap
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: k8s-powercap
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "k8s-powercap.serviceAccountName" . }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.webhook.enable }}
            - name: ENABLE_WEBHOOKS
              value: "true"
            {{- else }}
            - name: ENABLE_WEBHOOKS
              value: "false"
            {{- end }}
            - name: AGENT_IMAGE
              value: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag | default .Chart.AppVersion }}"
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            - /manager
          args:
            {{- if .Values.leaderElect }}
            - --leader-elect
            {{- end }}
            - --health-probe-bind-address={{ .Values.healthProbe.bindAddress }}
            {{- if .Values.metrics.enable }}
            - --metrics-bind-address={{ .Values.metrics.bindAddress }}
            - --metrics-secure={{ .Values.metrics.secureMetrics }}
            {{- end }}
            {{- if .Values.webhook.enable }}
            - --webhook-cert-path={{ .Values.webhook.certDir }}
            - --webhook-cert-name={{ .Values.webhook.certName }}
            - --webhook-cert-key={{ .Values.webhook.certKeyName }}
            {{- end }}
          ports:
            {{- if .Values.webhook.enable }}
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
            {{- end }}
            {{- if .Values.metrics.enable }}
            - containerPort: 8080
              name: metrics
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            {{- if .Values.webhook.enable }}
            - mountPath: {{ .Values.webhook.certDir }}
              name: webhook-certs
              readOnly: true
            {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        {{- if .Values.webhook.enable }}
        - name: webhook-certs
          secret:
            secretName: {{ include "k8s-powercap.fullname" . }}-webhook-cert
        {{- end }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
