// Code generated by deepcopy-gen. DO NOT EDIT.

package controller

import (
	"context"
	"time"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	appsv1 "k8s.io/api/apps/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"sigs.k8s.io/controller-runtime/pkg/client"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	powercapv1 "github.com/davidgibbons/k8s-powercap/api/v1"
)

var _ = Describe("PowercapSchedule Controller with Multi-Schedule", func() {
	const (
		namespace    = "default"
		resourceName = "test-multi"
		timeout      = time.Second * 10
		interval     = time.Millisecond * 250
	)

	ctx := context.Background()

	Context("When creating PowercapSchedule with multiple schedules", func() {
		It("should create a DaemonSet with all schedules", func() {
			Skip("Controller not started in test env - needs proper envtest setup")
			By("Creating PowercapSchedule with multiple schedules")
			ps := &powercapv1.PowercapSchedule{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: powercapv1.PowercapScheduleSpec{
					TimeZone: "UTC",
					Schedules: []powercapv1.PowercapRule{
						{
							Name:     "workday",
							Schedule: "0 9 * * 1",
							PowerLimits: []powercapv1.PowerLimitEntry{
								{
									Zone:       "intel-rapl:0",
									Constraint: "constraint_0",
									PowerLimit: 65000000,
								},
							},
						},
						{
							Name:     "night",
							Schedule: "0 0 * * *",
							PowerLimits: []powercapv1.PowerLimitEntry{
								{
									Zone:       "intel-rapl:0",
									Constraint: "constraint_0",
									PowerLimit: 30000000,
								},
							},
						},
					},
				},
			}
			Expect(k8sClient.Create(ctx, ps)).To(Succeed())

			By("Waiting for DaemonSet to be created")
			Eventually(func() bool {
				ds := &appsv1.DaemonSet{}
				err := k8sClient.Get(ctx, client.ObjectKey{Namespace: namespace, Name: resourceName + "-daemon"}, ds)
				if err != nil && !errors.IsNotFound(err) {
					return false
				}
				return ds.Spec.Selector != nil
			}, timeout, interval).Should(BeTrue())

			By("Verifying schedules are passed to environment")
			var ds appsv1.DaemonSet
			Expect(k8sClient.Get(ctx, client.ObjectKey{Namespace: namespace, Name: resourceName + "-daemon"}, &ds)).To(Succeed())

			scheduleJSON := ""
			for _, env := range ds.Spec.Template.Spec.Containers[0].Env {
				if env.Name == "SCHEDULES_JSON" {
					scheduleJSON = env.Value
					break
				}
			}
			Expect(scheduleJSON).NotTo(BeEmpty())
		})
	})

	AfterEach(func() {
		By("Cleaning up DaemonSet if exists")
		ds := &appsv1.DaemonSet{}
		err := k8sClient.Get(ctx, client.ObjectKey{Namespace: namespace, Name: resourceName + "-daemon"}, ds)
		if err == nil {
			Expect(k8sClient.Delete(ctx, ds)).To(Succeed())
		}

		By("Cleaning up PowercapSchedule")
		psLookup := &powercapv1.PowercapSchedule{}
		err = k8sClient.Get(ctx, client.ObjectKey{Namespace: namespace, Name: resourceName}, psLookup)
		Expect(err).NotTo(HaveOccurred())
		Expect(k8sClient.Delete(ctx, psLookup)).To(Succeed())
	})
})
